# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73c4dfda7eee40b2858916bc3be531f94defb491e1c09a9d0f700b841fffbbf201d5f5325bc70146b1fa3dda7e5c056eef48ad0aa741b17131ed511fc8f608cf

test:
  secret_key_base: 426383ae22f3c16bb686208596ea04f9380c6df4bb2ecfef3179dfc66c6734f5bb9cedcd8f3c83191334f4d853193fee69b95c8466f46c961b70637e0f035d8b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
